spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password:
    initialization-mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
cors:
  originPatterns: http://localhost:3000/
aws:
  s3:
    bucket:
      name:
        cooking_app: test-template-2023-03-05
